import React, { useState } from 'react';
import axios from 'axios';
import { motion, AnimatePresence } from 'framer-motion';
import { GitPullRequest, ExternalLink, CheckCircle2, AlertCircle, FileCode, MessageSquare } from 'lucide-react';

const DevOpsHub: React.FC<{ user: any }> = ({ user }) => {
  const [loading, setLoading] = useState(false);
  const [prResult, setPrResult] = useState<{ link: string; id: number } | null>(null);
  const [error, setError] = useState<string | null>(null);
  
  const [formData, setFormData] = useState({
    source_branch: `genie/update-${new Date().getTime()}`,
    target_branch: 'main',
    title: 'Update: dbt models generated by Genie',
    description: 'Este PR foi gerado automaticamente pelo assistente Genie.',
    sql_path: 'dbt/models/example.sql',
    sql_content: '',
    yml_path: 'dbt/models/schema.yml',
    yml_content: '',
    comment: 'feat: add new models from Genie analysis'
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setPrResult(null);

    try {
      const res = await axios.post(`http://localhost:8000/api/devops/pr?email=${user.user.email}`, formData);
      setPrResult({ link: res.data.pr_link, id: res.data.pr_id });
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Erro ao processar PR no Azure DevOps.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8 animate-fade-in max-w-5xl mx-auto">
      <header>
        <h1 className="text-4xl font-extrabold text-slate-900 font-outfit mb-2">DevOps & CI/CD Hub</h1>
        <p className="text-slate-500">Automatize a criação de Pull Requests no Azure DevOps</p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <motion.div className="glass card border border-slate-200" initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}>
          <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
            <GitPullRequest className="h-5 w-5 text-green-500" />
            Configuração da Branch e PR
          </h2>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Branch de Origem</label>
                <input 
                  type="text" 
                  value={formData.source_branch}
                  onChange={e => setFormData({...formData, source_branch: e.target.value})}
                  className="input-field text-sm"
                  required
                />
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Branch de Destino</label>
                <input 
                  type="text" 
                  value={formData.target_branch}
                  onChange={e => setFormData({...formData, target_branch: e.target.value})}
                  className="input-field text-sm"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Título do PR</label>
              <input 
                type="text" 
                value={formData.title}
                onChange={e => setFormData({...formData, title: e.target.value})}
                className="input-field text-sm"
                required
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Comentário do Commit</label>
              <input 
                type="text" 
                value={formData.comment}
                onChange={e => setFormData({...formData, comment: e.target.value})}
                className="input-field text-sm"
                required
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Descrição</label>
              <textarea 
                value={formData.description}
                onChange={e => setFormData({...formData, description: e.target.value})}
                className="input-field min-h-[100px] text-sm resize-none"
              />
            </div>

            <button type="submit" disabled={loading} className="btn-primary w-full py-4 mt-6">
              {loading ? 'Processando no Azure...' : <><GitPullRequest size={20} /> Criar Pull Request</>}
            </button>
          </form>
        </motion.div>

        <div className="space-y-6">
          <motion.div className="glass card border border-slate-200" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}>
            <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
              <FileCode className="h-5 w-5 text-blue-500" />
              Arquivos de Transformação
            </h2>
            <div className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Caminho do Model SQL</label>
                <input 
                  type="text" 
                  value={formData.sql_path}
                  onChange={e => setFormData({...formData, sql_path: e.target.value})}
                  className="input-field text-sm font-mono"
                  required
                />
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase mb-2">SQL Content</label>
                <textarea 
                  value={formData.sql_content}
                  onChange={e => setFormData({...formData, sql_content: e.target.value})}
                  className="input-field min-h-[120px] text-sm font-mono resize-none bg-slate-50"
                  placeholder="SELECT * FROM ..."
                  required
                />
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase mb-2">YAML Documentation (Opcional)</label>
                <textarea 
                  value={formData.yml_content}
                  onChange={e => setFormData({...formData, yml_content: e.target.value})}
                  className="input-field min-h-[80px] text-sm font-mono resize-none bg-slate-50"
                  placeholder="models: ..."
                />
              </div>
            </div>
          </motion.div>

          <AnimatePresence>
            {prResult && (
              <motion.div 
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="p-6 rounded-[28px] bg-green-50 border border-green-100 shadow-xl shadow-green-100/20"
              >
                <div className="flex items-center gap-3 text-green-700 mb-4">
                  <CheckCircle2 className="h-6 w-6" />
                  <h3 className="text-lg font-bold">Pull Request Criado!</h3>
                </div>
                <p className="text-sm text-green-600 mb-6 leading-relaxed">
                  As alterações foram commitadas e o Pull Request <strong>#{prResult.id}</strong> já está aberto no Azure DevOps.
                </p>
                <a 
                  href={prResult.link} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center justify-center gap-2 bg-green-600 text-white py-3 rounded-xl font-bold text-sm hover:bg-green-700 transition shadow-lg shadow-green-600/30"
                >
                  <ExternalLink size={16} />
                  Ver PR no Azure DevOps
                </a>
              </motion.div>
            )}

            {error && (
              <motion.div 
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="p-6 rounded-[28px] bg-red-50 border border-red-100 flex items-start gap-4"
              >
                <AlertCircle className="h-6 w-6 text-red-500 shrink-0" />
                <div>
                  <h3 className="text-sm font-bold text-red-800 mb-1">Falha na Automação</h3>
                  <p className="text-xs text-red-600">{error}</p>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
};

export default DevOpsHub;
